jupyterhub:
  hub:
    db:
      pvc:
        # This gonna store logs
        storage: 10Gi
  auth:
    google:
      callbackUrl: "https://utoronto.2i2c.cloud/hub/oauth_callback"
  proxy:
    https:
      hosts:
      - utoronto.2i2c.cloud
      - jupyter.utoronto.ca
